### ISSUE TITLE
v1- Report / Visualise Gathered Metrics

### ISSUE THREAD

**Issue by osahon-okungbowa** [CivicActions/ckanext-edscrapers#80]
### Situation: 
We needed to know how the project was progressing, so we gathered metrics on scraping performance. Now, we need to report these gathered metrics in an easy way, to facilitate quick decision-making and progress-reporting

### Tasks

- [x] Create an easily accessible and usable dashboard 

- [x] provide reports/visualisations on important metrics gathered

- [x] provide some periodic trends / progress reporting on metrics

- [x] create an overall indicator/summary of scraping progress

- [x] provide visualise comparison of  between Datopian and AIR scraping

### Acceptance
- [x] Dashboard is available on a public url/link
- [x] Dashboard contains simple. 'live' reports/visualisations on important metrics gathered
- [x] Dashboard contains periodic / time-series graphs showing trends on metrics
- [x] Dashboard contains RAG summary
- [x] Dashboard contains comparison report and visualisation between Datopian and AIR scraping

**Comment by nightsh** [comment]
My ETA for this is 2-3 days, out of which we already spent about 2, so not much left. One more day to provide time for unexpected issues.
We're about to publish the first working implementation today, which leaves one dev day to improve it.
