### ISSUE TITLE
Uniform I/O between transformers, tools and dashboard

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-edscrapers#88]
What we have now:
![image](https://user-images.githubusercontent.com/1579997/77892916-fda1ba80-727b-11ea-916a-47ff99cde5d7.png)

Target:
![image](https://user-images.githubusercontent.com/1579997/77893654-dac3d600-727c-11ea-94b0-d0c51468d62b.png)

**Tasks:**

* dump everything in XLSX files
* load everything from XLSX sheets instead of individual files
* generate one file per transformer (except datajson)
* use the new files in dashboard

**Acceptance criteria:**

* [ ] All transformers dump in XLSX
* [ ] The `name` parameter will generate a new sheet, instead of a new file
* [ ] Everything works as expected, with the new data files

> Note: The deprecated `compare` tool will be ignored for now, as well as its output. It will be subject to another task related to stats.
