### ISSUE TITLE
Scraper for FSA

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-edscrapers#90]
Federal Student Aid is an organization that publishes a lot of relevant data for the portal. The main website where everything is published is studentaid.gov.

**Tasks:**

* create a crawler for the FSA site
* add a parser (or more) to extract resources
* verify that it produces usable output
* manually test a few pages to validate output

**Acceptance criteria:**

* [x] Crawler visits all the pages on studentaid.gov
* [x] Parser extracts resources from all pages with data files
* [x] JSON output is usable by transformers
