### ISSUE TITLE
Phase 3 - Improve metadata quality P9 (NCES) parser

### ISSUE THREAD

**Issue by osahon-okungbowa** [CivicActions/ckanext-edscrapers#97]
## Description
On the basis of the results from the first runs/output from P9. The parser output needs to be improved both in terms of content and metadata quality.

## Tasks
- [x] based on the output from prior runs of P9, review the output content and identify possible areas for improvement
- [x] Implement improvements on parsers based on identified areas
- [x] Review all parsers and identify if number of parsers can be reduced from current number (4)
- [x] After refactoring and improvements, ensure all parsers still work as expected

## Acceptance Criteria
- [x] parser shows a marked improvement in content output
- [x] parsers still generate acceptable data.json after refactoring/improvements
- [x] metadata data has been improved, compare using weighted system if possible

[JIRA CARD](https://open-data-ed.atlassian.net/browse/OD-561)
